default.greeting: Welcome to 

my:
  greeting: ${default.greeting} spring cloud config server
  list:
      values: One,Two,Three,Four
db:
  connection: "{connectionString:'http://__from config server',userName:'foo',password:'pass'}"
  host: configServer
  port: 8888

server.port: 8090

management.endpoints.web.exposure.include: "*"

spring:
  profiles:
    active: test
