default.greeting: Welcome to 

my:
  greeting: ${default.greeting} my world
  list:
      values: One,Two,Three
db:
  connection: "{connectionString:'http://__',userName:'foo',password:'pass'}"
  host: localhost
  port: 3309

server.port: 8090

management.endpoints.web.exposure.include: "*"

spring:
  profiles:
    active: test